# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e9DvDmeK5PAa-fajTA3HwoMGe6jQ6cWD
"""

!pip install streamlit

import streamlit as st
import pandas as pd

st.title("Job Listing Clusters")

df = pd.read_csv('/content/clustered_jobs.csv')
clusters = df['Cluster'].unique()

cluster_selected = st.sidebar.multiselect("Select clusters", clusters)

if cluster_selected:
    filtered = df[df['Cluster'].isin(cluster_selected)]
    st.write(filtered)
else:
    st.write(df)